server:
  port: 8086
spring:
  application:
    name: review-service
  datasource:
    url: jdbc:h2:mem:reviews
    driver-class-name: org.h2.Driver
    username: penta
    password: bar

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/