spring:
  application:
    name: api-gateway
server:
  port: 8080
zuul:
  routes:
    id-movie-service: 
      path: /movies-service/**
      url: movie-service
    id-review-service: 
      path: /review-service/**
      url: review-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/