spring:
  application:
    name: discovery-service
server:
  port: 8761

eureka:
  client:
    # Server doesnot required to register it self hence set to false
    registerWithEureka: false
    # Server Does not required to fetch the registry it self
    fetchRegistry: false